package swp.koi.model.enums;

public enum AuctionRequestStatusEnum {
    PENDING,
    INSPECTION_IN_PROGRESS,
    INSPECTION_PASSED,
    INSPECTION_FAILED,
    PENDING_MANAGER_OFFER,
    PENDING_BREEDER_OFFER,
    APPROVE,
    REJECT,
    CANCELLED,
    WAITING_FOR_PAYMENT
}
